import { stableHash } from './core.js';
export class AnalyticsService {
 constructor({db,retentionDays=180}){this.db=db;this.retentionDays=retentionDays;}
 async record({guildId,name,subjectType=null,subjectId=null,dimensions={},metrics={},privacyClass='aggregate',idempotencyKey}){const row=(await this.db.query(`INSERT INTO analytics_events(guild_id,event_name,subject_type,subject_id,dimensions,metrics,privacy_class,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(idempotency_key) DO NOTHING RETURNING *`,[guildId,name,subjectType,subjectId,JSON.stringify(dimensions),JSON.stringify(metrics),privacyClass,idempotencyKey])).rows[0];return {recorded:Boolean(row),id:row?.id};}
 async aggregate(day=new Date().toISOString().slice(0,10)){const {rows}=await this.db.query(`SELECT guild_id,event_name,dimensions,count(*)::int count,jsonb_agg(metrics) metrics FROM analytics_events WHERE occurred_at >= $1::date AND occurred_at < $1::date+1 GROUP BY guild_id,event_name,dimensions`,[day]);for(const row of rows){const sums={};for(const metrics of row.metrics)for(const [key,value] of Object.entries(metrics??{}))if(Number.isFinite(Number(value)))sums[key]=(sums[key]??0)+Number(value);await this.db.query(`INSERT INTO analytics_daily(guild_id,day,event_name,dimensions_hash,dimensions,count,sums) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(guild_id,day,event_name,dimensions_hash) DO UPDATE SET count=excluded.count,sums=excluded.sums,updated_at=now()`,[row.guild_id,day,row.event_name,stableHash(row.dimensions),JSON.stringify(row.dimensions),row.count,JSON.stringify(sums)]);}return rows.length;}
 async summary(guildId,{from=new Date(Date.now()-30*864e5),to=new Date()}={}){const {rows}=await this.db.query(`SELECT event_name,count(*)::int count,COALESCE(sum((metrics->>'amount_minor')::numeric) FILTER(WHERE metrics?'amount_minor'),0)::text amount_minor FROM analytics_events WHERE guild_id=$1 AND occurred_at >= $2 AND occurred_at < $3 GROUP BY event_name ORDER BY event_name`,[guildId,from,to]);return {guildId,from:from.toISOString(),to:to.toISOString(),events:Object.fromEntries(rows.map(r=>[r.event_name,{count:r.count,amountMinor:r.amount_minor}]))};}
 async enforceRetention(){const result=await this.db.query(`DELETE FROM analytics_events WHERE occurred_at < now()-($1::text||' days')::interval OR (privacy_class='identifiable' AND occurred_at < now()-interval '30 days')`,[this.retentionDays]);return result.rowCount;}
 dimensionsHash(value){return stableHash(value);}
}
