import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { evaluatePolicy } from '../foundation/policy.js';

export class NativeError extends Error { constructor(code,message,details={}) { super(message); this.name='NativeError'; this.code=code; this.details=details; } }
export const stableHash=(value)=>createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex');
export const secureToken=(bytes=24)=>randomBytes(bytes).toString('base64url');
export function safeEqual(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&timingSafeEqual(x,y);}
export function assertTransition(current,next,map){if(!map[current]?.includes(next))throw new NativeError('invalid_transition',`${current} cannot transition to ${next}`,{current,next});}
export function authorize(ctx,{domain,risk='medium',permissions=[],consent=false,financial=false,behavior}){const decision=evaluatePolicy({domain,risk,behavior,autonomy:ctx.autonomy??'operator',actor:ctx.actor??{},requiredPermissions:permissions,approval:ctx.approval,consent,confirmedFinancialScope:financial});if(!decision.allowed)throw new NativeError(decision.requiresApproval?'approval_required':'authorization_denied',decision.reason);return decision;}
export async function transaction(db,fn){const c=await db.connect();try{await c.query('BEGIN');const out=await fn(c);await c.query('COMMIT');return out;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
export async function audit(db,ctx,event){await db.query(`INSERT INTO audit(action,domain,risk,decision,reason,correlation_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)`,[event.action,event.domain,event.risk??'medium',event.decision??'allowed',event.reason??null,ctx.correlationId??null,JSON.stringify({...event.metadata,discordGuildId:ctx.guildId,discordActorId:ctx.actor?.id})]);}
export async function idempotent(db,scope,key,input,work){if(!key)throw new NativeError('missing_idempotency_key','An idempotency key is required');const hash=stableHash(input);return transaction(db,async c=>{const prior=(await c.query('SELECT * FROM native_idempotency WHERE scope=$1 AND idempotency_key=$2 FOR UPDATE',[scope,key])).rows[0];if(prior){if(prior.input_hash!==hash)throw new NativeError('idempotency_conflict','Key was used with different input');if(prior.status==='completed')return {...prior.result,idempotent:true};if(prior.status==='running')throw new NativeError('operation_in_progress','Operation is already running');}await c.query(`INSERT INTO native_idempotency(scope,idempotency_key,input_hash,status) VALUES($1,$2,$3,'running') ON CONFLICT(scope,idempotency_key) DO UPDATE SET status='running',error=NULL,updated_at=now()`,[scope,key,hash]);try{const result=await work(c);await c.query(`UPDATE native_idempotency SET status='completed',result=$3,updated_at=now() WHERE scope=$1 AND idempotency_key=$2`,[scope,key,JSON.stringify(result)]);return result;}catch(error){await c.query(`UPDATE native_idempotency SET status='failed',error=$3,updated_at=now() WHERE scope=$1 AND idempotency_key=$2`,[scope,key,JSON.stringify({code:error.code,message:error.message})]);throw error;}});}
export function actorContext(interaction){return {guildId:interaction.guildId,actor:{id:interaction.user.id,authenticated:true,guildMember:interaction.inGuild(),bot:interaction.user.bot,isOwner:interaction.guild?.ownerId===interaction.user.id,permissions:interaction.memberPermissions?.toArray?.()??[]},autonomy:'operator',approval:{status:'approved'}};}
