import { NativeError, authorize, audit, idempotent } from './core.js';
const actionTool={warn:null,timeout:'member.timeout',kick:'member.kick',ban:'member.ban',unban:'member.unban'};
export class ModerationService {
 constructor({db,queue,tools,analytics,config={}}){Object.assign(this,{db,queue,tools,analytics});this.config={escalation:[{points:1,action:'warn'},{points:3,action:'timeout'},{points:5,action:'ban'}],reasonTemplates:config.reasonTemplates??{},...config};}
 async openCase(input,ctx){authorize(ctx,{domain:'moderation',risk:'medium',permissions:['ModerateMembers']});return idempotent(this.db,'moderation.case',input.idempotencyKey,input,async c=>{const summary=input.summary||this.config.reasonTemplates[input.reasonCode];if(!summary)throw new NativeError('reason_required','A reason or configured reason template is required');return (await c.query(`INSERT INTO moderation_cases(guild_id,member_id,opened_by,severity,reason_code,summary,metadata) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[ctx.guildId,input.memberId,ctx.actor.id,input.severity,input.reasonCode,summary,JSON.stringify({source:input.source??'manual'})])).rows[0];}).then(async row=>{for(const e of input.evidence??[])await this.addEvidence(row.id,e,ctx);await audit(this.db,ctx,{action:'moderation.case.open',domain:'moderation',risk:'medium',metadata:{caseId:row.id}});return row;});}
 async addEvidence(caseId,evidence,ctx){authorize(ctx,{domain:'moderation',risk:'low',permissions:['ModerateMembers']});if(!evidence.sha256&&!evidence.payload)throw new NativeError('evidence_required','Evidence must include a hash or immutable payload');return (await this.db.query(`INSERT INTO moderation_evidence(case_id,added_by,kind,uri,sha256,payload) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[caseId,ctx.actor.id,evidence.kind,evidence.uri??null,evidence.sha256??null,JSON.stringify(evidence.payload??{})])).rows[0];}
 async act(caseId,action,input,ctx){const risk=['kick','ban','unban'].includes(action)?'high':'medium',permissions=action==='ban'||action==='unban'?['BanMembers']:action==='kick'?['KickMembers']:['ModerateMembers'];authorize(ctx,{domain:'moderation',risk,permissions});return idempotent(this.db,'moderation.act',input.idempotencyKey,{caseId,action,...input},async c=>{const row=(await c.query('SELECT * FROM moderation_cases WHERE id=$1 FOR UPDATE',[caseId])).rows[0];if(!row)throw new NativeError('not_found','Moderation case not found');if(row.status!=='open')throw new NativeError('invalid_transition','Case is not open');const tool=actionTool[action],receipt=tool?await this.tools.invoke(tool,{guildId:ctx.guildId,userId:row.member_id,reason:input.reason??row.summary,...(action==='timeout'?{durationMs:input.durationMs}:{})},{...ctx,idempotencyKey:`moderation:${caseId}:${action}`,approval:ctx.approval}):{verification:{verified:true},output:{warning:true}};if(!receipt.verification?.verified)throw new NativeError('verification_failed','Discord moderation action was not verified');const expires=action==='timeout'?new Date(Date.now()+input.durationMs):null;await c.query(`UPDATE moderation_cases SET action=$2,action_expires_at=$3,status=$4,updated_at=now() WHERE id=$1`,[caseId,action,expires,action==='unban'?'resolved':'open']);await c.query(`INSERT INTO moderation_receipts(case_id,action,discord_receipt,verified) VALUES($1,$2,$3,true)`,[caseId,action,JSON.stringify(receipt)]);return {caseId,action,expiresAt:expires,receipt};}).then(async result=>{if(result.expiresAt)await this.queue?.enqueue('native-jobs','moderation.expire',{caseId},{idempotencyKey:`moderation:expire:${caseId}`,jobOptions:{delay:Math.max(0,new Date(result.expiresAt)-Date.now())}});await this.analytics?.record({guildId:ctx.guildId,name:`moderation.${action}`,subjectType:'case',subjectId:caseId,idempotencyKey:`moderation:${caseId}:${action}`});return result;});}
 async recommend(memberId,guildId){const {rows}=await this.db.query(`SELECT severity FROM moderation_cases WHERE guild_id=$1 AND member_id=$2 AND created_at>now()-interval '180 days'`,[guildId,memberId]);const points=rows.reduce((n,r)=>n+r.severity,0);return {points,action:[...this.config.escalation].reverse().find(x=>points>=x.points)?.action??'none'};}
 async appeal(caseId,tickets,ctx){const c=(await this.db.query('SELECT * FROM moderation_cases WHERE id=$1',[caseId])).rows[0];if(!c)throw new NativeError('not_found','Case not found');const ticket=await tickets.create({idempotencyKey:`appeal:${caseId}:${ctx.actor.id}`,memberId:ctx.actor.id,categoryKey:'appeal',subject:`Appeal case ${c.sequence}`,message:'Moderation appeal'},ctx);await this.db.query('UPDATE moderation_cases SET appeal_ticket_id=$2,updated_at=now() WHERE id=$1',[caseId,ticket.id]);return ticket;}
 async expire(caseId){return (await this.db.query(`UPDATE moderation_cases SET action=NULL,action_expires_at=NULL,updated_at=now() WHERE id=$1 AND action_expires_at<=now() RETURNING *`,[caseId])).rows[0];}
 async recoverJobs(){const rows=(await this.db.query(`SELECT id,action_expires_at FROM moderation_cases WHERE action_expires_at IS NOT NULL`)).rows;for(const r of rows)await this.queue.enqueue('native-jobs','moderation.expire',{caseId:r.id},{idempotencyKey:`moderation:expire:${r.id}`,jobOptions:{delay:Math.max(0,new Date(r.action_expires_at)-Date.now())}});return rows.length;}
}
