import { createHash } from 'node:crypto';
import { NativeError, assertTransition, authorize, audit, idempotent } from './core.js';
const transitions={open:['claimed','waiting_member','escalated','closed'],claimed:['waiting_member','waiting_staff','escalated','closed'],waiting_member:['waiting_staff','escalated','closed'],waiting_staff:['waiting_member','claimed','escalated','closed'],escalated:['claimed','waiting_member','closed'],closed:['open']};
export class TicketService {
 constructor({db,queue,tools,analytics,config={}}){Object.assign(this,{db,queue,tools,analytics});this.config={openLimit:config.openLimit??3,duplicateMinutes:config.duplicateMinutes??10,slaMinutes:config.slaMinutes??60,...config};}
 async create(input,ctx){authorize(ctx,{domain:'support',risk:'low'});return idempotent(this.db,'ticket.create',input.idempotencyKey,input,async c=>{const active=await c.query(`SELECT * FROM tickets WHERE guild_id=$1 AND member_id=$2 AND status<>'closed' ORDER BY opened_at DESC FOR UPDATE`,[ctx.guildId,input.memberId]);if(active.rowCount>=this.config.openLimit)throw new NativeError('open_limit','Member has reached the open ticket limit');if(active.rows.some(t=>t.subject.toLowerCase()===input.subject.trim().toLowerCase()&&Date.now()-new Date(t.opened_at)<this.config.duplicateMinutes*60000))throw new NativeError('duplicate_ticket','A matching ticket was recently opened');const due=new Date(Date.now()+(input.slaMinutes??this.config.slaMinutes)*60000);const row=(await c.query(`INSERT INTO tickets(guild_id,member_id,category_key,subject,priority,tags,due_at,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[ctx.guildId,input.memberId,input.categoryKey,input.subject,input.priority??'normal',input.tags??[],due,JSON.stringify({panelId:input.panelId})])).rows[0];await c.query(`INSERT INTO ticket_events(ticket_id,actor_id,kind,visibility,body) VALUES($1,$2,'created','system',$3)`,[row.id,input.memberId,input.message??null]);return row;}).then(async row=>{await this.queue?.enqueue('native-jobs','ticket.sla',{ticketId:row.id},{idempotencyKey:`ticket:sla:${row.id}`,jobOptions:{delay:Math.max(0,new Date(row.due_at)-Date.now())}});await this.analytics?.record({guildId:ctx.guildId,name:'ticket.opened',subjectType:'ticket',subjectId:row.id,idempotencyKey:`ticket:${row.id}:opened`});await audit(this.db,ctx,{action:'ticket.create',domain:'support',risk:'low',metadata:{ticketId:row.id}});return row;});}
 async transition(ticketId,next,ctx,{note=null,assigneeId,priority,tags}={}){authorize(ctx,{domain:'support',risk:next==='closed'?'medium':'low',permissions:['ManageThreads']});const row=await idempotent(this.db,'ticket.transition',ctx.idempotencyKey,{ticketId,next,note,assigneeId,priority,tags},async c=>{const ticket=(await c.query('SELECT * FROM tickets WHERE id=$1 FOR UPDATE',[ticketId])).rows[0];if(!ticket)throw new NativeError('not_found','Ticket not found');assertTransition(ticket.status,next,transitions);const closed=next==='closed'?new Date():null,reopened=ticket.status==='closed'?new Date():null;const updated=(await c.query(`UPDATE tickets SET status=$2,assignee_id=COALESCE($3,assignee_id),priority=COALESCE($4,priority),tags=COALESCE($5,tags),first_response_at=CASE WHEN first_response_at IS NULL AND $6<>member_id THEN now() ELSE first_response_at END,closed_at=COALESCE($7,closed_at),reopened_at=COALESCE($8,reopened_at),updated_at=now() WHERE id=$1 RETURNING *`,[ticketId,next,assigneeId??null,priority??null,tags??null,ctx.actor.id,closed,reopened])).rows[0];await c.query(`INSERT INTO ticket_events(ticket_id,actor_id,kind,visibility,body,payload) VALUES($1,$2,$3,'staff',$4,$5)`,[ticketId,ctx.actor.id,next,note,JSON.stringify({from:ticket.status,to:next})]);return updated;});await audit(this.db,ctx,{action:`ticket.${next}`,domain:'support',risk:'medium',metadata:{ticketId}});return row;}
 async note(ticketId,body,ctx,{memberVisible=false}={}){authorize(ctx,{domain:'support',risk:'low',permissions:['ManageMessages']});return (await this.db.query(`INSERT INTO ticket_events(ticket_id,actor_id,kind,visibility,body) VALUES($1,$2,$3,$4,$5) RETURNING *`,[ticketId,ctx.actor.id,memberVisible?'message':'internal_note',memberVisible?'member':'staff',body])).rows[0];}
 async transcript(ticketId,ctx){authorize(ctx,{domain:'support',risk:'read'});const ticket=(await this.db.query('SELECT * FROM tickets WHERE id=$1',[ticketId])).rows[0];if(!ticket)throw new NativeError('not_found','Ticket not found');const events=(await this.db.query('SELECT actor_id,kind,visibility,body,created_at FROM ticket_events WHERE ticket_id=$1 ORDER BY created_at',[ticketId])).rows;const content=events.map(e=>`[${new Date(e.created_at).toISOString()}] ${e.kind} ${e.actor_id??'system'}: ${e.body??''}`).join('\n');const sha256=createHash('sha256').update(content).digest('hex');return (await this.db.query(`INSERT INTO ticket_transcripts(ticket_id,sha256,format,content) VALUES($1,$2,'text/plain',$3) RETURNING *`,[ticketId,sha256,content])).rows[0];}
 async closeByMember(ticketId,memberId,idempotencyKey){return idempotent(this.db,'ticket.member_close',idempotencyKey,{ticketId,memberId},async c=>{const ticket=(await c.query('SELECT * FROM tickets WHERE id=$1 FOR UPDATE',[ticketId])).rows[0];if(!ticket||ticket.member_id!==memberId)throw new NativeError('authorization_denied','Only the ticket member may close this ticket');if(ticket.status==='closed')return ticket;assertTransition(ticket.status,'closed',transitions);const row=(await c.query(`UPDATE tickets SET status='closed',closed_at=now(),updated_at=now() WHERE id=$1 RETURNING *`,[ticketId])).rows[0];await c.query(`INSERT INTO ticket_events(ticket_id,actor_id,kind,visibility,body) VALUES($1,$2,'closed','member','Closed by member')`,[ticketId,memberId]);return row;});}
 async satisfy(ticketId,memberId,score,comment){const ticket=(await this.db.query('SELECT * FROM tickets WHERE id=$1',[ticketId])).rows[0];if(!ticket||ticket.member_id!==memberId||ticket.status!=='closed')throw new NativeError('authorization_denied','Only the ticket member may rate a closed ticket');return (await this.db.query(`INSERT INTO ticket_satisfaction(ticket_id,member_id,score,comment) VALUES($1,$2,$3,$4) ON CONFLICT(ticket_id) DO UPDATE SET score=excluded.score,comment=excluded.comment RETURNING *`,[ticketId,memberId,score,comment])).rows[0];}
 async handleSla(ticketId){const row=(await this.db.query(`UPDATE tickets SET status='escalated',escalation_level=escalation_level+1,updated_at=now() WHERE id=$1 AND status<>'closed' AND due_at<=now() RETURNING *`,[ticketId])).rows[0];if(row){await this.db.query(`INSERT INTO ticket_events(ticket_id,kind,visibility,body) VALUES($1,'sla_escalated','system','SLA deadline exceeded')`,[ticketId]);await this.analytics?.record({guildId:row.guild_id,name:'ticket.sla_breached',subjectType:'ticket',subjectId:ticketId,idempotencyKey:`ticket:${ticketId}:sla:${row.escalation_level}`});}return row;}
 async recoverJobs(){const rows=(await this.db.query(`SELECT id,due_at FROM tickets WHERE status<>'closed' AND due_at IS NOT NULL`)).rows;for(const r of rows)await this.queue.enqueue('native-jobs','ticket.sla',{ticketId:r.id},{idempotencyKey:`ticket:sla:${r.id}`,jobOptions:{delay:Math.max(0,new Date(r.due_at)-Date.now())}});return rows.length;}
}
