import { scryptSync, randomInt } from 'node:crypto';
import { NativeError, authorize, audit, idempotent, safeEqual, secureToken } from './core.js';
export class BuiltInChallengeAdapter { create(){const a=randomInt(2,10),b=randomInt(2,10),salt=secureToken(12),answer=String(a+b);return {prompt:`Enter the result of ${a} + ${b}.`,stored:`${salt}:${scryptSync(answer,salt,32).toString('hex')}`};} verify(stored,answer){const [salt,hash]=stored.split(':');return safeEqual(scryptSync(String(answer).trim(),salt,32).toString('hex'),hash);} }
export class VerificationService {
 constructor({db,queue,tools,analytics,challenge=new BuiltInChallengeAdapter(),config={}}){Object.assign(this,{db,queue,tools,analytics,challenge});this.config={ttlMinutes:config.ttlMinutes??15,maxAttempts:config.maxAttempts??5,manualReviewRisk:config.manualReviewRisk??70,quarantineRisk:config.quarantineRisk??90,verifiedRoleId:config.verifiedRoleId,quarantineRoleId:config.quarantineRoleId,...config};}
 async begin(input,ctx){authorize(ctx,{domain:'verification',risk:'low'});return idempotent(this.db,'verification.begin',input.idempotencyKey,input,async c=>{const existing=(await c.query(`SELECT * FROM verification_sessions WHERE guild_id=$1 AND member_id=$2 AND status IN ('pending_rules','challenge','manual_review','quarantined') FOR UPDATE`,[ctx.guildId,input.memberId])).rows[0];if(existing)return existing;const status=input.riskScore>=this.config.quarantineRisk?'quarantined':input.riskScore>=this.config.manualReviewRisk?'manual_review':'pending_rules';return (await c.query(`INSERT INTO verification_sessions(guild_id,member_id,status,max_attempts,risk_score,expires_at,metadata) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[ctx.guildId,input.memberId,status,this.config.maxAttempts,input.riskScore??0,new Date(Date.now()+this.config.ttlMinutes*60000),JSON.stringify({joinedAt:input.joinedAt,signals:input.signals??[]})])).rows[0];}).then(async r=>{await this.queue?.enqueue('native-jobs','verification.expire',{sessionId:r.id},{idempotencyKey:`verification:expire:${r.id}`,jobOptions:{delay:Math.max(0,new Date(r.expires_at)-Date.now())}});return r;});}
 async acceptRules(sessionId,memberId){const challenge=this.challenge.create();const row=(await this.db.query(`UPDATE verification_sessions SET status='challenge',rules_accepted_at=now(),challenge_hash=$3,updated_at=now() WHERE id=$1 AND member_id=$2 AND status='pending_rules' AND expires_at>now() RETURNING *`,[sessionId,memberId,challenge.stored])).rows[0];if(!row)throw new NativeError('invalid_transition','Rules cannot be accepted for this session');return {sessionId,prompt:challenge.prompt,expiresAt:row.expires_at};}
 async answer(sessionId,memberId,answer,ctx){const result=await idempotent(this.db,'verification.answer',ctx.idempotencyKey,{sessionId,memberId,answerHash:String(answer).length},async c=>{const s=(await c.query('SELECT * FROM verification_sessions WHERE id=$1 FOR UPDATE',[sessionId])).rows[0];if(!s||s.member_id!==memberId)throw new NativeError('not_found','Verification session not found');if(new Date(s.expires_at)<=new Date()){await c.query(`UPDATE verification_sessions SET status='expired' WHERE id=$1`,[sessionId]);throw new NativeError('expired','Verification session expired');}if(s.status!=='challenge')throw new NativeError('invalid_transition','Session is not accepting answers');const attempts=s.attempts+1,ok=this.challenge.verify(s.challenge_hash,answer);if(!ok){const status=attempts>=s.max_attempts?'manual_review':'challenge';await c.query('UPDATE verification_sessions SET attempts=$2,status=$3,updated_at=now() WHERE id=$1',[sessionId,attempts,status]);return {verified:false,status,attempts,remaining:Math.max(0,s.max_attempts-attempts)};}await c.query(`UPDATE verification_sessions SET attempts=$2,status='verified',verified_at=now(),challenge_hash=NULL,updated_at=now() WHERE id=$1`,[sessionId,attempts]);return {verified:true,status:'verified',attempts};});if(result.verified&&this.config.verifiedRoleId){const receipt=await this.tools.invoke('member.roles',{guildId:ctx.guildId,userId:memberId,add:[this.config.verifiedRoleId],remove:this.config.quarantineRoleId?[this.config.quarantineRoleId]:[],reason:'Azure verification completed'},{...ctx,idempotencyKey:`verification:${sessionId}:role`,approval:{status:'approved'},actor:{id:ctx.actor.id,authenticated:true,guildMember:true,bot:false,isOwner:true,permissions:['ManageRoles']}});if(!receipt.verification?.verified)throw new NativeError('role_verification_failed','Verified role grant could not be verified');result.roleReceipt=receipt;}await this.analytics?.record({guildId:ctx.guildId,name:result.verified?'verification.completed':'verification.failed_attempt',subjectType:'member',subjectId:memberId,privacyClass:'identifiable',idempotencyKey:`verification:${sessionId}:${result.attempts}`});await audit(this.db,ctx,{action:'verification.answer',domain:'verification',risk:'low',metadata:{sessionId,verified:result.verified}});return result;}
 async review(sessionId,decision,ctx){authorize(ctx,{domain:'verification',risk:'medium',permissions:['ManageRoles']});if(!['verified','denied','quarantined'].includes(decision))throw new NativeError('invalid_input','Unsupported review decision');return (await this.db.query(`UPDATE verification_sessions SET status=$2,verified_at=CASE WHEN $2='verified' THEN now() ELSE verified_at END,updated_at=now() WHERE id=$1 AND status IN ('manual_review','quarantined') RETURNING *`,[sessionId,decision])).rows[0]??(()=>{throw new NativeError('invalid_transition','Session cannot be reviewed')})();}
 async expire(sessionId){return (await this.db.query(`UPDATE verification_sessions SET status='expired',challenge_hash=NULL,updated_at=now() WHERE id=$1 AND status IN ('pending_rules','challenge') AND expires_at<=now() RETURNING *`,[sessionId])).rows[0];}
 async recoverJobs(){const rows=(await this.db.query(`SELECT id,expires_at FROM verification_sessions WHERE status IN ('pending_rules','challenge')`)).rows;for(const r of rows)await this.queue.enqueue('native-jobs','verification.expire',{sessionId:r.id},{idempotencyKey:`verification:expire:${r.id}`,jobOptions:{delay:Math.max(0,new Date(r.expires_at)-Date.now())}});return rows.length;}
}
