import { Events } from 'discord.js';
import { DiscordEventStore } from './event-store.js';
import { ContextAssembler } from './context.js';
import { EngagementPolicy } from './engagement.js';
import { DiscordToolRegistry } from './tool-runtime.js';
import { registerDiscordTools } from './tool-definitions.js';
import { withCorrelation } from '../foundation/logger.js';

const observed=[Events.MessageCreate,Events.MessageUpdate,Events.MessageDelete,Events.MessageReactionAdd,Events.MessageReactionRemove,Events.InteractionCreate,Events.GuildMemberAdd,Events.GuildMemberUpdate,Events.GuildMemberRemove,Events.GuildRoleCreate,Events.GuildRoleUpdate,Events.GuildRoleDelete,Events.ChannelCreate,Events.ChannelUpdate,Events.ChannelDelete,Events.ThreadCreate,Events.ThreadUpdate,Events.ThreadDelete,Events.GuildBanAdd,Events.GuildBanRemove,Events.AutoModerationActionExecution,Events.AutoModerationRuleCreate,Events.AutoModerationRuleUpdate,Events.AutoModerationRuleDelete,Events.GuildUpdate,Events.InviteCreate,Events.InviteDelete,Events.GuildScheduledEventCreate,Events.GuildScheduledEventUpdate,Events.GuildScheduledEventDelete,Events.WebhooksUpdate];
export function createDiscordRuntime({client,runtime,config,logger,memory=null}){
 const store=new DiscordEventStore(runtime.db),context=new ContextAssembler({db:runtime.db,maxTokens:config.discord.contextTokens,recentLimit:config.discord.contextMessages,semanticSearch:async({guildId,userId,query,limit})=>memory?.enabled?memory.search({query,guildId,userId,limit}):[]}),engagement=new EngagementPolicy({cooldownMs:config.discord.engagementCooldownMs,passiveThreshold:config.discord.passiveThreshold});
 const tools=registerDiscordTools(new DiscordToolRegistry({repositories:runtime.repositories,db:runtime.db,logger}));const listeners=[];
 for(const eventName of observed){const listener=(...args)=>withCorrelation(null,async()=>{try{const entity=eventName===Events.MessageUpdate?args[1]:args[0];const extra=eventName.includes('Reaction')?{reaction:args[0]?.emoji?.identifier,userId:args[1]?.id,resourceId:args[0]?.message?.id,guildId:args[0]?.message?.guildId,channelId:args[0]?.message?.channelId}:{};await store.ingest(eventName,entity,extra);if(eventName===Events.MessageCreate||eventName===Events.MessageUpdate)await routeMessage(entity,eventName===Events.MessageUpdate);}catch(err){logger.error({err,eventName},'Discord event ingestion failed');}});client.on(eventName,listener);listeners.push([eventName,listener]);}
 async function routeMessage(message,isEdit){if(message.partial)await message.fetch().catch(()=>null);const botId=client.user.id;const decision=engagement.decide({authorBot:message.author?.bot,webhookId:message.webhookId,selfAuthored:message.author?.id===botId,isDM:!message.guildId,mentionsAzure:message.mentions?.users?.has(botId),repliesToAzure:message.reference?.messageId?await message.channel.messages.fetch(message.reference.messageId).then(m=>m.author.id===botId).catch(()=>false):false,activeTask:false,ownerCommand:message.guild?.ownerId===message.author?.id&&/^azure[,!:\s]/i.test(message.content),channelId:message.channelId,threadId:message.channel?.isThread?.()?message.channelId:null,userId:message.author?.id,content:message.content,question:/\?\s*$/.test(message.content),azureRelevant:/\bazure\b/i.test(message.content),recentAzureContext:false,lowSignal:message.content.trim().length<3,isEdit,materialEdit:isEdit&&Boolean(message.editedTimestamp)});if(!decision.engage)return;await message.channel.sendTyping();const assembled=await context.assemble({messageId:message.id,guildId:message.guildId,channelId:message.channel?.isThread?.()?message.channel.parentId:message.channelId,threadId:message.channel?.isThread?.()?message.channelId:null,userId:message.author.id});if(!runtime.agent?.converse)return;const response=await runtime.agent.converse({message,context:assembled,decision});if(response){const sent=await message.reply({content:String(response).slice(0,2000),allowedMentions:{parse:[],repliedUser:false}});engagement.recordResponse(decision.scopeKey,sent.id);if(memory?.enabled&&config.memory.ingestion)memory.remember({guildId:message.guildId??null,userId:message.author.id,kind:'exchange',content:`User: ${message.content}\nAzure: ${String(response).slice(0,1500)}`,metadata:{discordChannelId:message.channelId}}).then((r)=>logger.debug?.({stored:r.stored},'semantic exchange remembered')).catch((err)=>logger.error?.({err},'semantic memory ingestion failed'));}}
 return{store,context,engagement,tools,close:async()=>{for(const [n,l] of listeners)client.off(n,l);}};
}
