import { createHash } from 'node:crypto';
const sortById=(items)=>items.sort((a,b)=>String(a.id).localeCompare(String(b.id)));
const json=(v)=>v?.toJSON?.()??v;
export function normalizeGuildSnapshot(guild) {
  const channels=sortById([...guild.channels.cache.values()].map(c=>({id:c.id,name:c.name,type:c.type,parentId:c.parentId??null,position:c.rawPosition??c.position??0,nsfw:Boolean(c.nsfw),topic:c.topic??null,rateLimitPerUser:c.rateLimitPerUser??0,permissionOverwrites:sortById([...c.permissionOverwrites.cache.values()].map(o=>({id:o.id,type:o.type,allow:o.allow.bitfield.toString(),deny:o.deny.bitfield.toString()})))})));
  const roles=sortById([...guild.roles.cache.values()].map(r=>({id:r.id,name:r.name,color:r.color,position:r.rawPosition??r.position,permissions:r.permissions.bitfield.toString(),hoist:r.hoist,mentionable:r.mentionable,managed:r.managed})));
  const snapshot={guild:{id:guild.id,name:guild.name,description:guild.description??null,icon:guild.icon??null,banner:guild.banner??null,verificationLevel:guild.verificationLevel,explicitContentFilter:guild.explicitContentFilter,defaultMessageNotifications:guild.defaultMessageNotifications,afkChannelId:guild.afkChannelId??null,afkTimeout:guild.afkTimeout,systemChannelId:guild.systemChannelId??null,rulesChannelId:guild.rulesChannelId??null,publicUpdatesChannelId:guild.publicUpdatesChannelId??null,preferredLocale:guild.preferredLocale,features:[...guild.features].sort()},channels,roles,emojis:sortById([...guild.emojis.cache.values()].map(e=>({id:e.id,name:e.name,animated:e.animated,available:e.available,managed:e.managed}))),stickers:sortById([...(guild.stickers?.cache?.values?.()??[])].map(s=>({id:s.id,name:s.name,description:s.description,tags:s.tags,type:s.type,format:s.format}))),scheduledEvents:sortById([...(guild.scheduledEvents?.cache?.values?.()??[])].map(json)),capturedAt:new Date().toISOString()};
  return snapshot;
}
export const snapshotHash=(snapshot)=>createHash('sha256').update(JSON.stringify({...snapshot,capturedAt:undefined})).digest('hex');
export function diffSnapshots(before,after){const changes=[];walk('',before,after,changes);return {fromGuildId:before?.guild?.id,toGuildId:after?.guild?.id,changes,hasChanges:changes.length>0};}
function walk(path,a,b,out){if(JSON.stringify(a)===JSON.stringify(b)||path==='/capturedAt')return;if(Array.isArray(a)&&Array.isArray(b)&&a.every(x=>x?.id)&&b.every(x=>x?.id)){const am=new Map(a.map(x=>[x.id,x])),bm=new Map(b.map(x=>[x.id,x]));for(const id of new Set([...am.keys(),...bm.keys()]))walk(`${path}/${id}`,am.get(id),bm.get(id),out);return;}if(a&&b&&typeof a==='object'&&typeof b==='object'&&!Array.isArray(a)&&!Array.isArray(b)){for(const k of new Set([...Object.keys(a),...Object.keys(b)]))walk(`${path}/${k}`,a[k],b[k],out);return;}out.push({op:a===undefined?'add':b===undefined?'remove':'replace',path:path||'/',before:a,after:b});}
