import test from 'node:test';import assert from 'node:assert/strict';import {newDb,DataType} from 'pg-mem';import {readFile} from 'node:fs/promises';
import {DiscordEventStore} from '../src/discord/event-store.js';import {ContextAssembler} from '../src/discord/context.js';import {EngagementPolicy} from '../src/discord/engagement.js';import {DiscordToolRegistry,z,ToolError} from '../src/discord/tool-runtime.js';import {diffSnapshots,snapshotHash} from '../src/discord/snapshot.js';
async function db(){const m=newDb();m.public.registerFunction({name:'gen_random_uuid',returns:DataType.uuid,impure:true,implementation:()=>crypto.randomUUID()});m.public.none(`
CREATE TABLE guilds(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),discord_id text UNIQUE NOT NULL,name text,settings jsonb DEFAULT '{}',created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),discord_id text UNIQUE NOT NULL,username text,profile jsonb DEFAULT '{}',created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE conversations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid,channel_id text NOT NULL,thread_id text,status text DEFAULT 'active',metadata jsonb DEFAULT '{}',created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),conversation_id uuid NOT NULL,discord_id text UNIQUE NOT NULL,author_id uuid,content text,metadata jsonb DEFAULT '{}',deleted_at timestamptz,referenced_message_id text,last_discord_edited_at timestamptz,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE message_revisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),message_id uuid NOT NULL,revision integer NOT NULL,content text,metadata jsonb DEFAULT '{}',created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now(),UNIQUE(message_id,revision));
CREATE TABLE memories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid,user_id uuid,kind text,content text,metadata jsonb DEFAULT '{}',created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());CREATE TABLE semantic_memories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),guild_id uuid,user_id uuid,kind text DEFAULT 'fact',content text NOT NULL,metadata jsonb DEFAULT '{}',content_hash text UNIQUE NOT NULL,embedding text,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE tasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),status text,goal text,domain text,risk text,metadata jsonb DEFAULT '{}',updated_at timestamptz DEFAULT now());
CREATE TABLE user_aliases(discord_id text PRIMARY KEY,alias text NOT NULL,updated_at timestamptz DEFAULT now());
CREATE TABLE discord_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),gateway_key text UNIQUE NOT NULL,event_type text,guild_id text,channel_id text,thread_id text,user_id text,resource_id text,occurred_at timestamptz,correlation_id uuid,payload jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE tool_idempotency(idempotency_key text PRIMARY KEY,tool_name text,input_hash text,status text,result jsonb,error jsonb,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());`);return new (m.adapters.createPg().Pool)();}
const msg=(content='hi',extra={})=>({id:'100000000000000001',guildId:'200000000000000001',channelId:'300000000000000001',content,cleanContent:content,author:{id:'400000000000000001',username:'u',bot:false},attachments:new Map(),mentions:{users:new Map(),roles:new Map(),channels:new Map(),everyone:false},components:[],embeds:[],stickers:new Map(),createdAt:new Date('2025-01-01'),channel:{isThread:()=>false},...extra});
test('event dedupe and exact revisions',async()=>{const p=await db(),s=new DiscordEventStore(p);assert.equal((await s.ingest('messageCreate',msg())).duplicate,false);assert.equal((await s.ingest('messageCreate',msg())).duplicate,true);await s.ingest('messageUpdate',msg('edited',{editedAt:new Date('2025-01-02')}));assert.equal(Number((await p.query('select count(*) n from message_revisions')).rows[0].n),2);});
test('gateway payloads with BigInt snowflakes serialize safely',async()=>{const p=await db(),s=new DiscordEventStore(p);const result=await s.ingest('interactionCreate',{id:'100000000000000001',guildId:200000000000000001n,user:{id:'400000000000000001',username:'u'}},{userId:'400000000000000001'});assert.equal(result.duplicate,false);assert.equal(typeof result.event.payload.resource.guildId,'string');});
test('reference chain is exact and budgeted',async()=>{const p=await db(),s=new DiscordEventStore(p);await s.ingest('messageCreate',msg('root'));await s.ingest('messageCreate',msg('reply',{id:'100000000000000002',reference:{messageId:'100000000000000001',channelId:'300000000000000001',guildId:'200000000000000001'}}));const c=await new ContextAssembler({db:p,maxTokens:1000}).assemble({messageId:'100000000000000002',guildId:'200000000000000001',channelId:'300000000000000001',userId:'400000000000000001'});assert.deepEqual(c.exactReferenceChain.map(x=>x.content),['root','reply']);assert.ok(c.estimatedTokens<1200);});
test('engagement deterministic, cooldown and loop guard',()=>{let n=1000;const e=new EngagementPolicy({now:()=>n,cooldownMs:100});assert.equal(e.decide({isDM:true,channelId:'x'}).engage,true);e.recordResponse('x','1');assert.equal(e.decide({channelId:'x',content:'are you alive',loopRelevant:false,lowSignal:false}).reason,'cooldown');const g=new EngagementPolicy({now:()=>n,followUpMs:100,cooldownMs:50});g.recordResponse('x','1');n+=120;g.recordResponse('x','2');n+=120;assert.equal(g.decide({channelId:'x',content:'are you alive',loopRelevant:false,lowSignal:false}).reason,'loop_guard');assert.equal(e.decide({channelId:'x',authorBot:true}).reason,'no_chatter_loops');});
test('name mention without ping engages deterministically',()=>{let n=1000;const e=new EngagementPolicy({now:()=>n,cooldownMs:100});assert.equal(e.decide({channelId:'x',content:'hi loop',loopRelevant:true,lowSignal:false}).reason,'name_mention');assert.equal(e.decide({channelId:'x',content:'are you alive loop',loopRelevant:true,lowSignal:false}).reason,'name_mention');assert.equal(e.decide({channelId:'x',content:'are you alive',loopRelevant:false,lowSignal:false}).reason,'passive_observation');assert.equal(e.decide({channelId:'x',content:'hi loop',loopRelevant:true,lowSignal:true}).reason,'passive_observation');});
test('follow-up fragments after a bot reply engage without any name',()=>{let n=1000;const e=new EngagementPolicy({now:()=>n,cooldownMs:100});e.recordResponse('x','1');const d=e.decide({channelId:'x',content:'whyd u not answer what i asked?',question:true,lowSignal:false});assert.equal(d.reason,'follow_up');assert.equal(d.engage,true);const d2=e.decide({channelId:'x',content:'and again...',lowSignal:false});assert.equal(d2.engage,false);const d3=e.decide({channelId:'x',content:'what do you have on your memory?',question:true,lowSignal:false});assert.equal(d3.engage,true);});
test('standalone questions with task words engage below the old threshold',()=>{let n=1000;const e=new EngagementPolicy({now:()=>n});const d=e.decide({channelId:'x',content:'whyd u not answer what i asked?',question:true,loopRelevant:false,lowSignal:false});assert.equal(d.reason,'relevant_passive_message');assert.equal(d.engage,true);});
test('complaints engage even without names or questions',()=>{let n=1000;const e=new EngagementPolicy({now:()=>n});assert.equal(e.decide({channelId:'x',content:'ure not as smart as i thought',loopRelevant:false,lowSignal:false}).reason,'complaint');assert.equal(e.decide({channelId:'x',content:'ure definetly not smart',loopRelevant:false,lowSignal:false}).reason,'complaint');assert.equal(e.decide({channelId:'x',content:'are you alive',loopRelevant:false,lowSignal:false}).reason,'passive_observation');});
test('tool schema, authorization, idempotency, verification and compensation',async()=>{const p=await db();let calls=0,undone=0;const r=new DiscordToolRegistry({db:p});r.register({name:'x',domain:'conversation',risk:'low',requiredPermissions:['SendMessages'],schema:z.object({value:z.string()}),execute:async()=>({id:String(++calls)}),verify:async()=>({verified:true,resourceIds:['1']}),compensate:async()=>{undone++;return{};}});const ctx={db:p,idempotencyKey:'k',autonomy:'operator',actor:{authenticated:true,guildMember:true,permissions:['SendMessages']}};const a=await r.invoke('x',{value:'v'},ctx),b=await r.invoke('x',{value:'v'},ctx);assert.equal(calls,1);assert.equal(b.idempotent,true);await r.compensate('x',{input:{value:'v'},output:a.output},ctx);assert.equal(undone,1);await assert.rejects(()=>r.invoke('x',{value:1},{...ctx,idempotencyKey:'bad'}),e=>e.code==='invalid_input');await assert.rejects(()=>r.invoke('x',{value:'v'},{...ctx,idempotencyKey:'deny',actor:{authenticated:false}}),e=>e.code==='authorization_denied');});
test('verification failure and unsupported operations fail closed',async()=>{const r=new DiscordToolRegistry();r.register({name:'bad',domain:'conversation',risk:'read',schema:z.object({}),execute:async()=>({}),verify:async()=>({verified:false})});await assert.rejects(()=>r.invoke('bad',{}, {idempotencyKey:'x',autonomy:'advisor',actor:{authenticated:true,guildMember:true}}),e=>e.code==='verification_failed');await assert.rejects(()=>r.invoke('missing',{},{}),e=>e.code==='unsupported_operation');});
test('normalized snapshot diff ignores capture time and tracks resource changes',()=>{const a={guild:{id:'1',name:'a'},channels:[{id:'2',name:'x'}],capturedAt:'a'},b={guild:{id:'1',name:'b'},channels:[{id:'2',name:'y'},{id:'3',name:'z'}],capturedAt:'b'};const d=diffSnapshots(a,b);assert.equal(d.hasChanges,true);assert.ok(d.changes.some(x=>x.path==='/guild/name'));assert.notEqual(snapshotHash(a),snapshotHash(b));});
