import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { assertTransition, authorize, NativeError, safeEqual } from '../src/native/core.js';
import { BuiltInChallengeAdapter } from '../src/native/verification.js';
import { HmacPaymentAdapter, CommerceService } from '../src/native/commerce.js';

const actor={authenticated:true,guildMember:true,bot:false,isOwner:false,permissions:[]};
test('native migration includes all durable systems and idempotency constraints',async()=>{const sql=await readFile(new URL('../migrations/005_native_systems.sql',import.meta.url),'utf8');for(const table of ['tickets','ticket_events','verification_sessions','products','product_variants','carts','orders','payment_events','moderation_cases','moderation_evidence','marketing_consent','campaigns','campaign_deliveries','analytics_events','analytics_daily','native_idempotency'])assert.match(sql,new RegExp(`CREATE TABLE ${table}\\b`,'i'),table);assert.match(sql,/UNIQUE\(provider,event_id\)/i);assert.match(sql,/FOR UPDATE|reserved/i);});
test('state transition guard rejects invalid transitions',()=>{assert.doesNotThrow(()=>assertTransition('open','closed',{open:['closed']}));assert.throws(()=>assertTransition('closed','paid',{closed:[]}),e=>e.code==='invalid_transition');});
test('built-in captcha stores no plaintext and enforces exact answer',()=>{const challenge=new BuiltInChallengeAdapter(),created=challenge.create();assert.match(created.prompt,/Enter the result/);assert.doesNotMatch(created.stored,/Enter|result/);let answer;for(let i=0;i<30;i++)if(challenge.verify(created.stored,String(i))){answer=String(i);break;}assert.ok(answer);assert.equal(challenge.verify(created.stored,'999'),false);});
test('payment webhook adapter verifies signatures and rejects tampering',()=>{const adapter=new HmacPaymentAdapter({secret:'unit-secret'}),raw=JSON.stringify({type:'payment.succeeded',orderId:'o'}),signature=adapter.sign(raw);assert.equal(adapter.verify(raw,signature),true);assert.equal(adapter.verify(raw+'x',signature),false);assert.equal(safeEqual('a','bb'),false);});
test('commerce acceptable-use gate rejects credential trafficking',async()=>{const svc=new CommerceService({db:{query:async()=>{throw new Error('must not query');}},config:{}});await assert.rejects(()=>svc.upsertProduct({sku:'x',name:'Stolen account login',acceptableUse:'goods'}, {guildId:'g',actor:{...actor,isOwner:true},autonomy:'operator',approval:{status:'approved'}}),e=>e.code==='acceptable_use_denied');});
test('marketing policy requires consent and authorization',()=>{assert.throws(()=>authorize({actor,autonomy:'operator'},{domain:'marketing',risk:'low',consent:false}),e=>e.code==='authorization_denied');assert.doesNotThrow(()=>authorize({actor,autonomy:'operator'},{domain:'marketing',risk:'low',consent:true}));});
test('unauthorized and high-risk native actions are denied',()=>{assert.throws(()=>authorize({actor:{...actor,authenticated:false},autonomy:'operator'},{domain:'support',risk:'low'}),NativeError);assert.throws(()=>authorize({actor:{...actor,permissions:['BanMembers']},autonomy:'operator'},{domain:'moderation',risk:'high',permissions:['BanMembers']}),e=>e.code==='approval_required');});
