import { PermissionFlagsBits, SlashCommandBuilder } from 'discord.js';
import { panel, button, V2 } from '../ui/theme.js';
import { actorContext } from '../native/core.js';
export default {data:new SlashCommandBuilder().setName('server').setDescription('Operate Azure native server systems.')
 .addSubcommand(s=>s.setName('ticket').setDescription('Open a support ticket').addStringOption(o=>o.setName('subject').setDescription('Ticket subject').setRequired(true).setMaxLength(200)).addStringOption(o=>o.setName('category').setDescription('Configured category').setRequired(false)))
 .addSubcommand(s=>s.setName('verify').setDescription('Start verification'))
 .addSubcommand(s=>s.setName('store').setDescription('Show the legitimate-goods storefront'))
 .addSubcommand(s=>s.setName('marketing-optout').setDescription('Opt out of marketing').addStringOption(o=>o.setName('purpose').setDescription('Consent purpose').setRequired(true)))
 .addSubcommand(s=>s.setName('analytics').setDescription('Show a privacy-aware 30-day summary')),
 async execute(interaction,client){const n=client.runtime.native,sub=interaction.options.getSubcommand(),ctx=actorContext(interaction);if(!n)return interaction.reply({content:'Native systems are unavailable.',ephemeral:true});if(sub==='ticket'){const row=await n.tickets.create({idempotencyKey:`interaction:${interaction.id}`,memberId:interaction.user.id,categoryKey:interaction.options.getString('category')??'general',subject:interaction.options.getString('subject',true)},ctx);return interaction.reply({flags:V2,ephemeral:true,components:[panel({title:`TICKET ${row.sequence}`,body:`**${row.subject}**\nStatus: ${row.status}`,buttons:[button.neutral(`ticket:close:${row.id}`,'Close')],footer:'Azure support'})]});}if(sub==='verify'){const row=await n.verification.begin({idempotencyKey:`interaction:${interaction.id}`,memberId:interaction.user.id,riskScore:0,joinedAt:interaction.member?.joinedAt?.toISOString()},ctx);return interaction.reply({flags:V2,ephemeral:true,components:[panel({title:'VERIFICATION',body:row.status==='pending_rules'?'Review and accept the server rules to continue.':`Status: ${row.status}`,buttons:row.status==='pending_rules'?[button.primary(`verify:rules:${row.id}`,'Accept Rules')]:[]})]});}if(sub==='marketing-optout'){const row=await n.marketing.consent({memberId:interaction.user.id,purpose:interaction.options.getString('purpose',true),status:'opted_out',source:'member_command'},ctx);return interaction.reply({flags:V2,ephemeral:true,components:[panel({title:'OPTED OUT',body:`Consent for **${row.purpose}** is disabled.`})]});}if(sub==='analytics'){if(!interaction.memberPermissions?.has(PermissionFlagsBits.ManageGuild))return interaction.reply({content:'Manage Server permission is required.',ephemeral:true});const s=await n.analytics.summary(interaction.guildId);const body=Object.entries(s.events).map(([k,v])=>`**${k}** — ${v.count}`).join('\n')||'No events in this period.';return interaction.reply({flags:V2,ephemeral:true,components:[panel({title:'SERVER ANALYTICS',body,footer:'Aggregated, privacy-aware 30-day view'})]});}const products=(await client.runtime.db.query(`SELECT p.name,p.description,min(v.price_minor) price,v.currency FROM products p JOIN product_variants v ON v.product_id=p.id WHERE p.guild_id=$1 AND p.active AND v.active GROUP BY p.id,v.currency ORDER BY p.name LIMIT 20`,[interaction.guildId])).rows;return interaction.reply({flags:V2,components:[panel({title:'THE STORE',subtitle:'Legitimate digital goods only.',body:products.map(p=>`## ${p.name}\n${p.description??''}\nFrom **${p.price} ${p.currency}**`).join('\n\n')||'No products are available.',footer:'Purchases require acceptable-use acceptance.'})]});}}
