import { randomUUID } from 'node:crypto';
import { snapshotHash, diffSnapshots } from '../discord/snapshot.js';

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
export class WorkflowError extends Error { constructor(code,message,details={}) { super(message); this.code=code; this.details=details; } }
export class SafeWorkflowExecutor {
  constructor({ store, tools, snapshotReader, permissionResolver, maxSnapshotAgeMs=60_000, concurrency=2, now=()=>new Date(), rateLimitPause=sleep }) { Object.assign(this,{store,tools,snapshotReader,permissionResolver,maxSnapshotAgeMs,concurrency,now,rateLimitPause}); }
  async start({ proposal, decision, actor, dryRun=false }) {
    if (!decision?.decision?.startsWith('approve')) throw new WorkflowError('not_approved','An approval decision is required');
    if (Number(decision.proposal_revision ?? decision.revision) !== proposal.revision) throw new WorkflowError('revision_mismatch','Approval is not for the current proposal revision');
    const approvedStepIds=decision.approved_step_ids??decision.approvedStepIds;
    const execution=await this.store.createExecution({proposalId:proposal.id,proposalRevision:proposal.revision,guildId:proposal.guildId,status:'queued',dryRun,approvedStepIds,metadata:{actorId:actor.id,beforeSnapshotHash:proposal.beforeSnapshotHash}});
    return this.execute({execution,proposal,actor});
  }
  async execute({execution,proposal,actor}) {
    return this.store.transaction(async(tx)=>{await tx.lockGuild(proposal.guildId); const current=await tx.getExecution(execution.id); if(['completed','rolled_back','cancelled'].includes(current?.status))return{execution:current,idempotent:true};
      await tx.updateExecution(execution.id,{status:'running'}); const fresh=await this.snapshotReader(proposal.guildId); const age=this.now()-new Date(fresh.capturedAt); if(age>this.maxSnapshotAgeMs)throw new WorkflowError('stale_snapshot','Preflight snapshot is stale',{age});
      if(snapshotHash(fresh)!==proposal.beforeSnapshotHash)throw new WorkflowError('snapshot_conflict','Guild changed after proposal',{diff:diffSnapshots({...(proposal.beforeSnapshot??fresh),capturedAt:fresh.capturedAt},fresh)});
      const tier=proposal.tiers.find((t)=>t.id===proposal.selectedTierId), approved=new Set(current.approved_step_ids??current.approvedStepIds), selected=proposal.machinePlan.steps.filter((s)=>approved.has(s.id));
      const permissions=await this.permissionResolver(proposal.guildId,actor); const missing=tier.requiredPermissions.filter((p)=>!permissions.includes(p)); if(missing.length)throw new WorkflowError('permission_denied','Required Discord permissions are missing',{missing});
      await tx.reserveBudget({guildId:proposal.guildId,domain:proposal.domain,amount:tier.estimates.costUsd,executionId:execution.id}); if(current.dry_run??current.dryRun){const receipt=await tx.createReceipt({executionId:execution.id,kind:'dry_run',status:'completed',evidence:[{preflightSnapshotHash:snapshotHash(fresh),steps:selected.map(s=>s.id)}],verification:{verified:true,noMutations:true}});await tx.updateExecution(execution.id,{status:'completed'});await tx.releaseBudget(execution.id);return{executionId:execution.id,status:'completed',dryRun:true,receipt};}
      try {const completed=new Set((await tx.listSteps(execution.id)).filter(s=>s.status==='completed').map(s=>s.step_key??s.stepId)); const evidence=[]; for(const stage of [...new Set(selected.map(s=>s.stage))].sort((a,b)=>a-b)){const live=await tx.getExecution(execution.id);if(['cancelling','cancelled'].includes(live.status)){await tx.updateExecution(execution.id,{status:'cancelled'});await tx.releaseBudget(execution.id);return{executionId:execution.id,status:'cancelled'};} const ready=selected.filter(s=>s.stage===stage); for(let i=0;i<ready.length;i+=this.concurrency){const batch=ready.slice(i,i+this.concurrency);const settled=await Promise.allSettled(batch.map(async step=>{if(completed.has(step.id))return(await tx.getStep(execution.id,step.id)).receipt;const blocked=step.dependsOn.find(d=>!completed.has(d));if(blocked)throw new WorkflowError('dependency_failed',`Dependency ${blocked} is incomplete`);const key=`workflow:${execution.id}:${step.id}`;await tx.saveStep({executionId:execution.id,stepId:step.id,stage,status:'running',idempotencyKey:key});try{const receipt=await this.tools.invoke(step.tool,step.input,{idempotencyKey:key,autonomy:'operator',approval:{status:'approved'},actor});if(!receipt.verification?.verified||!receipt.evidenceId)throw new WorkflowError('verification_failed',`Step ${step.id} lacks verified evidence`);await tx.saveStep({executionId:execution.id,stepId:step.id,stage,status:'completed',idempotencyKey:key,receipt,compensation:receipt.compensation});completed.add(step.id);evidence.push(receipt);return receipt;}catch(error){await tx.saveStep({executionId:execution.id,stepId:step.id,stage,status:'failed',idempotencyKey:key,error:{code:error.code,message:error.message}});throw error;}}));const failures=settled.filter(x=>x.status==='rejected');if(failures.length)throw new WorkflowError('partial_failure','A stage partially failed',{stage,failures:failures.map(x=>({code:x.reason.code,message:x.reason.message}))});}await this.rateLimitPause(0);}
        const after=await this.snapshotReader(proposal.guildId);if(this.now()-new Date(after.capturedAt)>this.maxSnapshotAgeMs)throw new WorkflowError('verification_failed','Postcondition read is stale');const receipt=await tx.createReceipt({executionId:execution.id,kind:'execution',status:'completed',evidence,verification:{verified:true,freshReadHash:snapshotHash(after),diff:diffSnapshots(fresh,after)}});await tx.updateExecution(execution.id,{status:'completed',metadata:{...(current.metadata??{}),beforeSnapshotHash:proposal.beforeSnapshotHash,afterSnapshotHash:snapshotHash(after)}});await tx.releaseBudget(execution.id,'committed');return{executionId:execution.id,status:'completed',receipt};
      }catch(error){await tx.updateExecution(execution.id,{status:'failed',metadata:{error:{code:error.code,message:error.message}}});await tx.releaseBudget(execution.id);throw error;}
    });
  }
  async cancel(executionId){const execution=await this.store.getExecution(executionId);if(!execution||['completed','failed','rolled_back','cancelled'].includes(execution.status))return false;await this.store.updateExecution(executionId,{status:'cancelling'});return true;}
  async recover(loadProposal,actorResolver){const rows=await this.store.recoverableExecutions(),results=[];for(const execution of rows){if(execution.status==='cancelling'){await this.store.updateExecution(execution.id,{status:'cancelled'});results.push({id:execution.id,status:'cancelled'});continue;}try{results.push(await this.execute({execution,proposal:await loadProposal(execution.proposal_id),actor:await actorResolver(execution)}));}catch(error){results.push({id:execution.id,status:'failed',error:error.message});}}return results;}
}
