export class PostgresAutonomyStore {
  constructor(db) { this.db = db; }
  async transaction(fn) { const client = await this.db.connect(); try { await client.query('BEGIN'); const value = await fn(new PostgresAutonomyStore(client)); await client.query('COMMIT'); return value; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release?.(); } }
  async createProposal(proposal) { return (await this.db.query(`INSERT INTO proposals(task_id,guild_discord_id,revision,status,goal,domain,risk,before_snapshot_hash,before_captured_at,content_hash,diff,tiers,selected_tier_id,machine_plan,estimates) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`, [proposal.taskId,proposal.guildId,proposal.revision,proposal.status,proposal.goal,proposal.domain,proposal.risk,proposal.beforeSnapshotHash,proposal.beforeCapturedAt,proposal.contentHash,JSON.stringify(proposal.diff),JSON.stringify(proposal.tiers),proposal.selectedTierId,JSON.stringify(proposal.machinePlan),JSON.stringify(proposal.tiers.find((t)=>t.id===proposal.selectedTierId)?.estimates??{})])).rows[0]; }
  async getProposal(id) { return (await this.db.query('SELECT * FROM proposals WHERE id=$1',[id])).rows[0] ?? null; }
  async updateProposal(id, patch) { const keys=Object.keys(patch), values=Object.values(patch).map((v)=>typeof v==='object'&&v!==null?JSON.stringify(v):v); return (await this.db.query(`UPDATE proposals SET ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')},updated_at=now() WHERE id=$${keys.length+1} RETURNING *`,[...values,id])).rows[0]; }
  async createApprovalToken(data) { return (await this.db.query(`INSERT INTO approval_tokens(proposal_id,proposal_revision,actor_discord_id,guild_discord_id,token_hash,expires_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[data.proposalId,data.proposalRevision,data.actorId,data.guildId,data.tokenHash,data.expiresAt])).rows[0]; }
  async lockApprovalToken(tokenHash) { return (await this.db.query('SELECT * FROM approval_tokens WHERE token_hash=$1 FOR UPDATE',[tokenHash])).rows[0] ?? null; }
  async findApprovalToken(tokenHash) { return (await this.db.query('SELECT * FROM approval_tokens WHERE token_hash=$1',[tokenHash])).rows[0] ?? null; }
  async consumeApprovalToken(id,{decision,actorId}) { return (await this.db.query('UPDATE approval_tokens SET consumed_at=now(),decision=$2,decided_by_discord_id=$3 WHERE id=$1 AND consumed_at IS NULL RETURNING *',[id,decision,actorId])).rows[0]; }
  async recordProposalDecision(data) { const row=(await this.db.query(`INSERT INTO proposal_decisions(proposal_id,proposal_revision,actor_discord_id,guild_discord_id,decision,approved_step_ids,reason,authorization) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[data.proposalId,data.revision,data.actorId,data.guildId,data.decision,data.approvedStepIds,data.reason,JSON.stringify(data.authorization)])).rows[0]; const status=data.decision.startsWith('approve')?'approved':data.decision==='reject'?'rejected':'changes_requested'; await this.db.query('UPDATE proposals SET status=$2,updated_at=now() WHERE id=$1',[data.proposalId,status]); return row; }
  async latestDecision(proposalId,revision) { return (await this.db.query('SELECT * FROM proposal_decisions WHERE proposal_id=$1 AND proposal_revision=$2 ORDER BY created_at DESC LIMIT 1',[proposalId,revision])).rows[0]??null; }
  async reserveBudget({guildId,domain,amount,executionId}) { return (await this.db.query(`INSERT INTO budget_reservations(guild_discord_id,domain,amount,execution_id,status) VALUES($1,$2,$3,$4,'reserved') RETURNING *`,[guildId,domain,amount,executionId])).rows[0]; }
  async releaseBudget(executionId,status='released') { await this.db.query('UPDATE budget_reservations SET status=$2,updated_at=now() WHERE execution_id=$1 AND status=$3',[executionId,status,'reserved']); }
  async createExecution(data) { return (await this.db.query(`INSERT INTO workflow_executions(proposal_id,proposal_revision,guild_discord_id,status,dry_run,approved_step_ids,metadata) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[data.proposalId,data.proposalRevision,data.guildId,data.status,data.dryRun,data.approvedStepIds,JSON.stringify(data.metadata??{})])).rows[0]; }
  async getExecution(id) { return (await this.db.query('SELECT * FROM workflow_executions WHERE id=$1',[id])).rows[0]??null; }
  async updateExecution(id,patch) { const keys=Object.keys(patch), values=Object.values(patch).map((v)=>typeof v==='object'&&v!==null?JSON.stringify(v):v); return (await this.db.query(`UPDATE workflow_executions SET ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')},updated_at=now() WHERE id=$${keys.length+1} RETURNING *`,[...values,id])).rows[0]; }
  async lockGuild(guildId) { const value=[...String(guildId)].reduce((n,c)=>((n*31+c.charCodeAt(0))|0),0); await this.db.query('SELECT pg_advisory_xact_lock($1)',[value]); }
  async getStep(executionId,stepId) { return (await this.db.query('SELECT * FROM workflow_steps WHERE execution_id=$1 AND step_key=$2',[executionId,stepId])).rows[0]??null; }
  async saveStep(data) { return (await this.db.query(`INSERT INTO workflow_steps(execution_id,step_key,stage,status,idempotency_key,receipt,error,compensation) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(execution_id,step_key) DO UPDATE SET status=excluded.status,receipt=excluded.receipt,error=excluded.error,compensation=excluded.compensation,updated_at=now() RETURNING *`,[data.executionId,data.stepId,data.stage,data.status,data.idempotencyKey,JSON.stringify(data.receipt??null),JSON.stringify(data.error??null),JSON.stringify(data.compensation??null)])).rows[0]; }
  async listSteps(executionId) { return (await this.db.query('SELECT * FROM workflow_steps WHERE execution_id=$1 ORDER BY stage,created_at',[executionId])).rows; }
  async createReceipt(data) { return (await this.db.query(`INSERT INTO workflow_receipts(execution_id,kind,status,evidence,verification,conflicts,irreversible) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[data.executionId,data.kind,data.status,JSON.stringify(data.evidence??[]),JSON.stringify(data.verification??{}),JSON.stringify(data.conflicts??[]),JSON.stringify(data.irreversible??[])])).rows[0]; }
  async recoverableExecutions() { return (await this.db.query("SELECT * FROM workflow_executions WHERE status IN ('queued','running','cancelling','rolling_back') ORDER BY created_at")).rows; }
}
export function hydrateProposal(row) { return { id:row.id,taskId:row.task_id,guildId:row.guild_discord_id,revision:Number(row.revision),status:row.status,goal:row.goal,domain:row.domain,risk:row.risk,beforeSnapshotHash:row.before_snapshot_hash,beforeCapturedAt:new Date(row.before_captured_at).toISOString(),contentHash:row.content_hash,diff:row.diff,tiers:row.tiers,selectedTierId:row.selected_tier_id,machinePlan:row.machine_plan }; }
